### ISSUE TITLE
Code not producing results as expected

### ISSUE THREAD

**Issue by AadilLatif** [tdcosim/SolarPV-DER-simulation-tool#33]
I have been trying to integrate the PV der model, but am running into issues.
The implementation can be found here

https://github.com/NREL/PyDSS/blob/dynamic_pv_model/PyDSS/pyControllers/Controllers/PvDynamic.py

the settings toml file associated with the simulation can be found here

https://github.com/NREL/PyDSS/blob/dynamic_pv_model/examples/dynamics/PV_example/Scenarios/base_case/pyControllerList/PvDynamic.toml

I am hoping you are able to help me figure out the error with my implementation

**Comment by sibyjackgrove** [comment]
@AadilLatif Thank you for the issue and sorry for the delay in reply. Could you point me to the code that creates the `PvDynamic` object so that I can run and recreate the error? Alternatively, could you post the error that you are getting.

**Comment by AadilLatif** [comment]
Hi,  the first link is my implementation. I am trying to interface it with OpenDSS. For this purpose, I am using PyDSS. I can hop on a 30-minute call to explain the implementation if needed.

**Comment by sibyjackgrove** [comment]
Sure, a call would be great. Do you want to have the call on Microsoft Teams?

**Comment by sibyjackgrove** [comment]
@AadilLatif Could you point me to an example script that I can run? I will clone the PyDSS repository and run it to recreate the error.

**Comment by AadilLatif** [comment]
I 

> Sure, a call would be great. Do you want to have the call on Microsoft Teams?

Yes, that would be great. Can you send me a few time slots that work for you? My email is aadil.latif@nrel.gov.  PyDSS is a large codebase, which is why I recommended doing a teams meeting. I can quickly show you how I set up the simulation.

**Comment by sibyjackgrove** [comment]
@AadilLatif  I just send a meeting invite with suggested timings. Please feel free to suggest other times.

**Comment by sibyjackgrove** [comment]
@AadilLatif I found the problem. It seems the pvder model was getting tripped due to the high voltage protection logic. This was caused because the rated voltage for the DER is lesser than the voltage to which it is being connected.
The rated voltage for the model was 173 Vrms (which is also the reference voltage for protection logic). But the grid voltage is 192 Vrms. So the model enters the high voltage zone (which has a threshold of 1.06*173 Vrms) and then trips at 1.5 s. Also, the Vdc rated voltage of 550 V is no sufficient to generate 192 Vrms at the inverter terminal.

The following changes can be made to fix this:
Line 46 in PvDynamic.py: `self._Vrms = abs(self._Va )/math.sqrt(2)`  -> `self._Vrms = 192.0`
Line 160 in config_der.json: `"Vdcrated":550.0 `-> `"Vdcrated":750.0 `(This is not absolutely necessary, but the Vdc link voltage will have oscillations otherwise). Note 750 V is the MPP voltage for this DER.

Another option if you don’t want to change the rated voltage. This will disable the protection logic.
Line 10 in PvDynamic.toml: `HVRT_ENABLE = true` -> `HVRT_ENABLE = false`

If you want more details on the settings used in the protection logic, please check: https://github.com/tdcosim/SolarPV-DER-simulation-tool/blob/master/pvder/templates.py#L112

Please let me know if it is working after making these changes.

**Comment by sibyjackgrove** [comment]
@AadilLatif is Closing this issue since I assume it has been resolved with the solution provided in the previous comment. Please feel free to reopen if the issue persists.
